const rulesShortCut = {
  text: 'Free Skating: <span>2:30 min. +/-10 sec.</span>',
  text1: '<li>Maximum of <span>five (5) jump elements</span> one of which must be an Axel type jump.</li><li>There must be up to <span>two (2)</span> jump combinations or <span>one (1)</span> jump combination <span>without</span> using the Euler (half-loop) and <span>one(1)</span> jump sequence. <li>Jump combinations and the jump sequence consist of two (2) jumps. In the jump sequence the second jump must be an Axel type jump with a direct step from the landing curve of the first jump into the take-off curve of the Axel jump.</li><li>An Euler (half-loop) when used in a jump combination or sequence between two listed jumps will be called but not considered as a listed jump, and will <span>not</span> counted in the number of the jumps of the concerned jump combination or sequence.</li><li>After the Euler <span>no change of foot</span> is allowed. An Euler can only be executed once.</li><li><span>Only one single jump and one double jump (including Double Axel)</span> can be repeated once.</li>',

  text2: '<li>There must be a maximum of <span>two (2) spins</span> of a different nature (abbreviation), one of which must be a <span>spin combination</span> and one must be a spin with <span>no change of position and no change of foot</span>.</li><li>The spin combination with a change of foot must have a minimum of eight (8) revolutions and without a change of foot with a minimum of six (6) revolutions.</li><li><span>Flying entry is allowed</span>. If with change of foot, only one level feature per foot will count.<li>Difficult variation of a <span>non-basic position</span> is <span>not counted as a feature</span> in this spin, this will be ignored by the Technical Panel</li><li>The spin in one position without change of foot must have a <span>minimum of six (6) revolutions</span>, must be done in a <span>basic</span> position (camel, sit, layback or upright) and will be called maximum level basic. <span>No level features are allowed in this spin</span>. 8 revolutions can be done but will not count as an attempted feature. Flying entry is not allowed.</li>',

  text3: '<li>There must be a maximum of one (1) step sequence fully utilizing the ice surface and <span>including at least one skating movement</span> such as a spiral, spread eagle, Ina Bauer, hydroblading etc. If the skating movement is missing, no Level will be given.</li><li><span>At least 2 difficult turns and steps</span> must be executed on clean edges for Level basic. The TWIZZLE needs to have <span>at least two (2) revolutions</span> to be counted.</li><li>The Technical Panel will not award the use of body movements for at least 1/3 of the pattern feature and the two combinations of 3 difficult turns on different feet feature.</li>',
// Intermedia novice rules
  text4: 'Free Skating: <span>2:30 min, +/-10 sec.</span>', 

  text5: '<li>Maximum of <span>5 jump elements</span> one of which must be an Axel type jump.</li><li>There may be up to <span>two (2)</span> jump combinations or <span>one (1)</span> jump combination without using the Euler (half-loop) and <span>one (1)</span> jump sequence.</li><li>Jump combinations and the jump sequence consist of <span>only two (2) jumps.</span> In the jump sequence the second jump must be an <span>Axel type jump</span> with a direct step from the landing curve of the first jump into the take-off curve of the Axel jump. One full revolution on the ice between the jumps (free foot can touch the ice, but without weight transfer) keeps the element in the frame of the definition of a jump sequence. Jumps executed in a jump sequence receive their full value.</li><li><span>An Euler(half-loop)</span> when used in a jump combination or sequence between two listed jumps <span>will be called but not considered as a listed jump</span>, and will <span>not be counted</span> in the number of the jumps of the concerned jump combination or sequence.</li><li>After the Euler(half-loop) <span>no change of foot is allowed</span>. An Euler (half-loop) can only be executed once in the Free Skating.</li><li><span>No triple or quadruple jumps are allowed.</span> Only <span>one</span> single jump and <span>one</span> double jump (including Double Axel) can be repeated once.</li>',//done

  text6: '<li>There must be a maximum of <span>two (2) spins of a different nature (abbreviation),</span> one of which must be a spin combination, and one must be a spin with no change of position.</li><li>The spin combination with a change of foot must have a minimum of <span>eight (8)</span> revolutions and without a change of foot with a minimum of <span>six (6)</span> revolutions, <span>flying entrance is not allowed.</span> If with change of foot, only <span>one level feature per foot</span> will count.</li><li>Difficult variation of non-basic position is <span>not counted</span> as a feature in <span>any</span> spin, this will ignored by the Technical Panel.</li><li>The spin in one position with a change of foot must have a <span>minimum of eight (8)</span> revolutions or spin in one position without change of foot must have a <span>minimum of six (6)</span> revolutions, <span>flying entrance is allowed.</span> If with change of foot, only <span>one level feature per foot</span> will count.',//done
};
  
// Advance novice rules
  const advanceNoviceRules = {
    sp: {
      ProgramDuration: '<li>Short Program: <span>2:20 min, +/-10 sec</span></li>',
      Jumps: '<li>a) <span>Single Axel Paulsen or double Axel Paulsen;</span></li><li>b) <span>Double or triple jump</span>, may not repeat jump a);</li> <li>c) <span>One jump combination</span> consisting of two double jumps or one double and one triple jump, <span>the second jump must be double or triple Toe Loop</span> (for season 2026/27), both jumps may not repeat jump a) or b).</li>',
      Spins: '<li>For girls: <span>Layback/sideways leaning spin or sit spin with no change of foot</span> (minimum six (6) revolutions) and no flying entrance (for season 2026/27).;<li>For boys: <span>Sit spin with change of foot</span> and no flying entrance (minimum of five (5) revolutions on each foot) (for season 2026/27).</li></li><li><span>Spin combination with only one change of foot</span> (minimum of five (5) revolutions on each foot), <span>flying entrance not allowed</span>.</li>',
      StepSiquence: '<li>One step sequence fully utilizing the ice surface.</li><li> For feature 4) Two combinations of 3 difficult turns on different feet: <span>the combinations must include forward outside counter and backward outside loop (for season 2026/27), they can be in the same combination or one in the first and the other in the second.</span></li><li> Only one difficult turn may be repeated once in the two combinations. <span>At least 2 difficult turns and steps must be executed on clean edges for Level basic.</span></li><li>The twizzle needs to have <span>at least two (2) revolutions</span> to be counted.</li>',
    },
    fp: {
      ProgramDuration: 'Free Skating: <span>3 min, +/-10 sec.</span>', 
      Jumps: '<li>Maximum of <span>5 jump elements</span> one of which must be an Axel type jump. There may be up to two (2) jump combinations or one (1) jump combination without using an <span>Euler (half loop)</span> and one (1) jump sequencw.</li><li>One jump combination or jump sequence can consist of up to <span>three (3) jumps</span>, the other up to <span>two (2) jumps.</span></li><li>A jump sequence consists of <span>two or three jumps of any number of revolutions,</span> in which the second and/or the third jump is an Axel type jump with a direct step from the landing curve of the first/second jump into the take-off curve of the Axel jump.</li><li>One full revolution on the ice between the jumps (free foot can touch the ice, but without weight transfer) keeps the element in the frame of the definition of a jump sequence. Jumps executed in a jump sequence receive their full value.<li>An <span>Euler (half-loop)</span> when used in a jump combination or sequence between two listed jumps will be called but will not be considered as a listed jump, and will not be counted in the number of the jumps of the concerned combination or sequence.</li><li>After the execution of the Euler (half-loop) <span>no change of foot is allowed</span>. An Euler (half-loop) can be executed only <span>once</span> in the Free Skating.</li><li>No quadruple jumps are allowed.</li><li>Any single, double (including Double Axel) or triple jump cannot be executed <span>more than twice in total</span>. Only <span>two triple jumps</span> can be repeated either in a jump combination or jump sequence.</li><li>The <span>same type of jump independent of revolutions</span> can be included not more than twotimes in the Free Skating program.</li>',
      Spins: '<li>There must be a <span>maximum of two (2) spins</span> of a different nature (abbreviation).</li><li> One spin must be a spin combination with a change of foot which must have a <span>minimum of eight (8) revolutions, a flying entrance is not allowed.</span></li><li>One spin must be a <span>flying camel spin without change of foot</span> which must have a minimum of six (6) revolutions, (for season 2026/27).</li>',
      ChoreoSiquence: 'There must be one Choreographic Sequence consisting of <span>at least two</span> different skating movements.'
    }
  };   
  
  // Junior Rules
  const spJuniorRules = {
    girls: {
      ProgramDuration: 'Short Program: <strong>2 minutes and 40 seconds</strong> (+- 10 seconds).',
      Jumps: '<li>Double <strong>Axel Paulsen</strong>;</li><li>Double or triple <strong>Lutz</strong> jump;</li><li>Jump combination consisting of a <strong>double and a triple jump or two triple</strong> jumps;</li><br><br><span>Remarks:</span><li>Only the <strong>prescribed</strong> double or triple jump is permitted.</li><li>The jump combination may consist of the <strong>same jump or another double or triple jump</strong>. However, for all categories the jumps included <strong>must be different</strong> than the solo jump.</li>', //finished
      Spins: '<li>Flying <strong>camel</strong> spin;</li><li><strong>Layback / sideways</strong> leaning spin or <strong>camel</strong> spin <strong>without</strong> change of foot;</li><li>Spin combination with only <strong>one</strong> change of foot;</li><br><br><span>Remarks:</span><li>Spin in <strong>one position and spin combination:</strong> if there is <strong>no spin</strong> position before and/or after the change of foot with at least <strong>three</strong> revolutions, the spin is not according to the requirements and <strong>no value</strong> will be given. <span>Except flying spins, spins cannot be commenced with a jump</span></li><li>Only the <strong>prescribed</strong> type of flying spin is permitted.</li><li>In <strong>flying spin</strong> a minimum of <strong>eight</strong> revolutions in the landing position which may be different from the flying position. No previous rotation on the ice before the take-off is permited.</li><li>The required eight revolutions can be executed in any variation of the landing position.</li><li>In <strong>layback or sideways leaning</strong> spin any position is permitted, as long as the basic layback or sideways leaning position is maintained for <strong>eight</strong> revolutions without rising to an upright position. After the required eight revolutions it is possible to execute the Biellmann position. <span>Change of foot is not allowed.</span></li><li>In the spin in <strong>one position</strong> without change of foot any variation(s) of the requite position can be executed. Minimum of <strong>eight</strong> revolutions in this position.</li><li> If the landing position of the Flying spin is <span>the same as in the Spin in one position</span>, the last performed of these two spins will not be counted, but will occupy a spin box.</li><li>The spin combination must include only <strong>one</strong> change of foot with not less than <strong>six</strong> revolutions on each foot.</li>', //finished
      StepSiquence: '<li>Step sequence <strong>fully utilizing</strong> the ice surface.</li><br><br><span>Remarks:</span><li>Unlisted jumps (any number of revolutions) and listed jumps (with maximum one and a half revolutions) <strong>may be</strong> included in the step sequence without any penalties. Listed jumps of not more than <strong>one and a half</strong> revolutions included in the sequence will not be called and will not occupy a box.' //finished
    },
    boys: {
      ProgramDuration: 'Short Program: <strong>2 minutes and 40 seconds</strong> (+- 10 seconds).',
      Jumps: '<li>Double or triple <strong>Axel Paulsen</strong>;</li><li>Double or triple <strong>Lutz</strong> jump;</li><li>Jump combination consisting of a <strong>double and a triple jump or two triple</strong> jumps;</li><br><br><span>Remarks:</span><li>When the <strong>triple Axel Paulsen</strong> is executed, it <strong>cannot</strong> be repeated again as a solo jump or in the jump combination.</li><li>Only the <strong>prescribed</strong> double or triple jump is permitted.</li><li>The jump combination may consist of the <strong>same jump or another double or triple jump</strong>. However, for all categories the jumps included <strong>must be different</strong> than the solo jump.</li>',// finished

      Spins: '<li>Flying <strong>camel</strong> spin;</li><li><strong>Sit</strong> spin with only <strong>one</strong> change of foot;</li><li>Spin combination with only <strong>one</strong> change of foot;</li><br><br><span>Remarks:</span><li>Spin in <strong>one</strong> position: Only the <span>prescribed</span> position is permitted to be executed. The spin must consist of <span>only one change of foot</span>, which may be executed in the form of a step over or a jump with not less than six revolutions on each foot in the chosen basic position.</li><li>The <span>spin combination</span> must include only one change of foot with not less than six revolutions on each foot. A change of foot may be executed in the form of a step over or a jump. The change of foot and the change of position may be made either at the same time or separately.</li>', //finished
      StepSiquence: '<li>Step sequence <strong>fully utilizing</strong> the ice surface.</li><br><br><span>Remarks:</span><li>Unlisted jumps (any number of revolutions) and listed jumps (with maximum one revolution) <strong>may be</strong> included in the step sequence without any penalties. Listed jumps of not more than <strong>one</strong> revolution included in the sequence will not be called and will not occupy a box.'
    }
  };

  const fpJuniorRules = {
    girls: {
      ProgramDuration: 'Free Skating: <strong>3 minutes and 30 seconds</strong> (+- 10 seconds).',
      Jumps: '<li>Maximum of <strong>six</strong> jump elements (one of which must be an <strong>Axel</strong> type jump);</li><br><br><strong>Jump Combinations and Jump Sequences:</strong><li>A jump combination and a jump sequence may consist of the same or another single, double, triple or quadruple jump.</li><li>There may be up to <span>two</span> jump combinations or <span>one</span> jump combination without using an Euler (half-loop) and one jump sequence in the Free Skating.</li><li>One jump combination or one jump sequence may consist of up to <span>three</span> jumps, the other one of up to <span>two</span> jumps. An <span>Euler (half-loop)</span> can only be executed once, in between two listed jumps, in Free Skating.</li<li>Quint jumps are not allowed.</li><br><br><strong>Repetitions:</strong><li>The same type of jump <span>independent of the number of revolutions</span> can be included not more than three times in the Free Skating program.</li><li>Any double jump (including double Axel) cannot be included more than <strong>twice</strong> in a Single’s Free Skating program (as a Solo Jump or a part of a Jump Combination / Sequence).</li><li>Of all <span>triple and quadruple and quint jumps</span> only two can be executed twice. Of the two repetitions <strong>only one</strong> can be a quadruple jump or quint jump. If both executions are as solo jumps, the second of these solo jumps will be attributed 80% of its numerical value according to the Scale of Value.</li><li>Triple and quadruple and quint jumps with the <strong>same name</strong> will be considered as <span>two different jumps.</span> No triple jump or quadruple jump or quint jump can be attempted <span>more than twice.</span></li>', // finished

      Spins: '<li>Maximum of <strong>three</strong> spins, one of which must be a <strong>spin combination</strong>, one a <strong>flying spin</strong> and one <strong>choreographic</strong> spin.</li><br><br><strong>Remarks:</strong><li>All Spins must be of a <spa>different character</span>. Any Spin with the same character (abbreviation) as the one executed before will be deleted (but will occupy a spinning box).</li><li>The spins must have a required minimum number of revolutions: <span>six</span> for the flying spin and <span>ten</span> for the spin combination.</li><br><br><strong>Choreographic Spin:</strong><li>A Choreographic Spin is a spin which enhances the choreography of the program and matches the music.</li><li>Must have a minimum of <span>3 consecutive revolutions</span> executed on <span>one or two</span> blades, with any basic or non-basic positions allowed. <span>Change of foot</span> is optional and can be done several times during the spin.</li><li>The Technical Panel identifies the Choreographic Spin and it will be confirmed once the <span>3 consecutive revolutions have been completed</span>.</li><li>This element has a fixed base value and will be evaluated by the judges in GOE only.</li>',  //finished

      ChoreoSiquence: '<li>Maximum of one choreographic sequence.</li><li>It consists of at least <span>two different</span> skating movements like spirals, arabesques, spread eagles, Ina Bauers, hydroblading, any jumps with maximum of two revolutions, spins, etc.</li><li>Steps and turns may be used to link the two or more different movements together.</li><li>Listed elements included in the Choreographic Sequence will not be called and will not occupy a box.</li><li>The pattern is not restricted, but the sequence must be clearly visible.</li>' //finished
    },
    boys: {
      ProgramDuration: 'Free Skating: <strong>3 minutes and 30 seconds</strong> (+- 10 seconds).',
      Jumps: '<li>Maximum of <strong>six</strong> jump elements (one of which must be an <strong>Axel</strong> type jump);</li><br><br><strong>Jump Combinations and Jump Sequences:</strong><li>A jump combination and a jump sequence may consist of the same or another single, double, triple or quadruple jump.</li><li>There may be up to <span>two</span> jump combinations or <span>one</span> jump combination without using an Euler (half-loop) and one jump sequence in the Free Skating.</li><li>One jump combination or one jump sequence may consist of up to <span>three</span> jumps, the other one of up to <span>two</span> jumps. An <span>Euler (half-loop)</span> can only be executed once, in between two listed jumps, in Free Skating.</li<li>Quint jumps are not allowed.</li><br><br><strong>Repetitions:</strong><li>The same type of jump <span>independent of the number of revolutions</span> can be included not more than three times in the Free Skating program.</li><li>Any double jump (including double Axel) cannot be included more than <strong>twice</strong> in a Single’s Free Skating program (as a Solo Jump or a part of a Jump Combination / Sequence).</li><li>Of all <span>triple and quadruple and quint jumps</span> only two can be executed twice. Of the two repetitions <strong>only one</strong> can be a quadruple jump or quint jump. If both executions are as solo jumps, the second of these solo jumps will be attributed 80% of its numerical value according to the Scale of Value.</li><li>Triple and quadruple and quint jumps with the <strong>same name</strong> will be considered as <span>two different jumps.</span> No triple jump or quadruple jump or quint jump can be attempted <span>more than twice.</span></li>', //finished
      
      Spins: '<li>Maximum of <strong>three</strong> spins, one of which must be a <strong>spin combination</strong>, one a <strong>flying spin</strong> and one <strong>choreographic</strong> spin.</li><br><br><strong>Remarks:</strong><li>All Spins must be of a <spa>different character</span>. Any Spin with the same character (abbreviation) as the one executed before will be deleted (but will occupy a spinning box).</li><li>The spins must have a required minimum number of revolutions: <span>six</span> for the flying spin and <span>ten</span> for the spin combination.</li><br><br><strong>Choreographic Spin:</strong><li>A Choreographic Spin is a spin which enhances the choreography of the program and matches the music.</li><li>Must have a minimum of <span>3 consecutive revolutions</span> executed on <span>one or two</span> blades, with any basic or non-basic positions allowed. <span>Change of foot</span> is optional and can be done several times during the spin.</li><li>The Technical Panel identifies the Choreographic Spin and it will be confirmed once the <span>3 consecutive revolutions have been completed</span>.</li><li>This element has a fixed base value and will be evaluated by the judges in GOE only.</li>', //finished

      ChoreoSiquence: '<li>Maximum of one choreographic sequence.</li><li>It consists of at least <span>two different</span> skating movements like spirals, arabesques, spread eagles, Ina Bauers, hydroblading, any jumps with maximum of two revolutions, spins, etc.</li><li>Steps and turns may be used to link the two or more different movements together.</li><li>Listed elements included in the Choreographic Sequence will not be called and will not occupy a box.</li><li>The pattern is not restricted, but the sequence must be clearly visible.</li>' //finished
    }
  };

// Senior Rules. Start senior with spins remarks
const spSeniorRules = {
  girls: {
    ProgramDuration: 'Short Program: <strong>2 minutes and 40 seconds</strong> (+- 10 seconds).',
    Jumps: '<li>Double or triple <strong>Axel Paulsen</strong>.</li><li>Triple jump.</li><li>Jump combination consisting of a double jump and a triple jump or two triple jumps.</li><br><br><span>Remarks:</span><li>Any triple jump is permitted.</li><li>The jump combination may consist of the <span>same</span> jump or <span>another</span> double or triple jump. However, for all categories the jumps included must be <span>different</span> than the solo jump.</li><li>If the same jump is executed as a solo jump and as a part of the jump combination, the repeated jump will not be counted (if this repetition is in a jump combination, only the individual jump which is not according to the above requirements will not be counted).</li><li>If an extra jump(s) is executed, only the individual jump(s) which is not according to requirements will have no value. The jumps are considered <strong>in the order</strong> of execution.</li>',  //finished

    Spins: '<li><strong>Flying</strong> spin.</li><li><strong>Layback / sideways</strong> leaning spin or <strong>sit</strong> or <strong>camel</strong> spin <span>without</span> change of foot.</li><li><strong>Spin combination</strong> with only <span>one</span> change of foot;</li><br><br><span>Remarks:</span><li>Any type of <span>flying spin</span> is permitted with landing position <strong>different</strong> than in the Spin in one position.</li><li>A minimum of <span>eight</span> revolutions in the landing position which <strong>may be different</strong> from the flying position.</li><li>layback or sideways leaning spin: <strong>any position is permitted,</strong> as long as the basic layback or sideways leaning position is maintained for <span>eight revolutions</span> without rising to an upright position. <strong>After the required eight revolutions</strong> it is possible to execute the Biellmann position.</li><li>The <strong>spin combination</strong> must include only <span>one</span> change of foot with not less than <span>six</span> revolutions on each foot.</li>',  // finished

    StepSiquence: '<li>Step sequence fully utilizing the ice surface.</li><li><strong>Unlisted jumps</strong> (any number of revolutions) and <strong>listed jumps</strong> (with maximum one revolution) may be included in the step sequence without any penalties. <strong>Listed jumps</strong> of not more than one revolution included in the sequence will not be called and will not occupy a box.</li>'  // finished
  },
  boys: {
    ProgramDuration: 'Short Program: <strong>2 minutes and 40 seconds</strong> (+- 10 seconds).',
    Jumps: '<li>Double or triple <strong>Axel Paulsen</strong>;</li><li>Triple or quadruple jump.</li><li>Jump combination consisting of a double jump and a triple jump or two triple jumps or a quadruple jump and a double jump or a triple jump.</li><br><br><span>Remarks:</span><li>When the triple <strong>Axel Paulsen</strong> is executed, it cannot be repeated again as a solo jump or in the jump combination.</li><li>Any triple or quadruple jump is permitted, when a quadruple jump is executed in jump combination, a different quadruple jump can be included as a solo jump.</li><li>The jump combination may consist of the <span>same jump or another</span> double, triple or quadruple jump. When a quadruple jump is executed in as a solo jump, a <span>different quadruple</span> jump can be included in the jump combination.</li><li>If the same jump is executed as a solo jump and as a part of the jump combination, the repeated jump will not be counted (if this repetition is in a jump combination, only the individual jump which is not according to the above requirements will not be counted).</li><li>If an extra jump(s) is executed, only the individual jump(s) which is not according to requirements will have no value. The jumps are considered <strong>in the order</strong> of execution.</li>', //finished

    Spins: '<li><strong>Flying</strong> spin.</li><li><strong>Camel</strong> spin or <strong>sit</strong> spin with only <span>one change of foot</span>;</li><li><strong>Spin combination</strong> with only <span>one change of foot</span>;</li><br><br><span>Remarks:</span><li>Any type of <span>flying spin</span> is permitted with landing position <strong>different</strong> than in the Spin in one position.</li><li>A minimum of <span>eight</span> revolutions in the landing position which <strong>may be different</strong> from the flying position.</li><li>The <strong>spin combination</strong> must include only <span>one</span> change of foot with not less than <span>six</span> revolutions on each foot.</li>', //finished

    StepSiquence: '<li>Step sequence fully utilizing the ice surface.</li><li><strong>Unlisted jumps</strong> (any number of revolutions) and <strong>listed jumps</strong> (with maximum one revolution) may be included in the step sequence without any penalties. <strong>Listed jumps</strong> of not more than one revolution included in the sequence will not be called and will not occupy a box.</li>'  // finished
  }
};

const fpSeniorRules = {
  girls: {
    ProgramDuration: 'Free Skating: <strong>4 minutes</strong> (+- 10 seconds).',

    Jumps: '<li>Maximum of <strong>six</strong> jump elements (one of which must be an Axel type jump).</li><br><br><strong>Remarks:</strong><li>Individual jumps can contain any number of revolutions.</li><li>A jump combinations and jump sequence may consist of the same or another single, double, triple or quadruple jump.</li><li>There may be up to <strong>two</strong> jump combination without using an Euler (half loop) and one jump sequence in the Free Skating.</li><li>One jump combination or one jump sequence may consist of up to <strong>three</strong> jumps, the other one up to <strong>two</strong> jumps.</li><li>An Euler (half-loop) can only be executed <strong>once</strong>, in between two listed jumps, in Free Skating.</li><li>The same type of jump <strong>independent of the number of revolutions</strong> can be included not more than three times in the Free Skating program.</li><li>Any double jump (including double Axel) cannot be included <strong>more than twice</strong> in a Single’s Free Skating program (as a Solo Jump or a part of a Jump Combination / Sequence).</li><li>Of all triple and quadruple jumps only two can be executed twice. Of the two repetitions only one can be a quadruple jump or quint jump.</li><li>If both executions are as solo jumps, the second of these solo jumps will be attributed 80% of its numerical value according to the Scale of Value.</li><li>Triple and quadruple and quint jumps with the <strong>same name</strong> will be considered as <span>two</span> different jumps. No triple jump or quadruple jump or quint jump can be attempted <span>more than twice</span></li>',

    Spins: '<li>Maximum of three spins, one of which must be a <span>spin combination</span>, one a <span>flying</span> spin and one <span>choreographic</span> spin.</li><li>All Spins must be of a different character. Any Spin with the <span>same character (abbreviation)</span> as the one executed before will be deleted (but will occupy a spinning box).</li><li>The spins must have a required minimum number of revolutions: <span>six</span> for the flying spin and <span>ten</span> for the spin combination, the lack of which must be reflected by Judges in their marking. These minimum number of required revolutions must be counted from the entry of the spin until its exit (except final wind-up in Spins in one position and Flying spins).</li><li>In the spin combination the change of foot is optional.</li><li>A Choreographic Spin must have a minimum of <span>3 consecutive revolutions</span> executed on one or two blades, with any basic or non-basic positions allowed. Change of foot is optional and can be done several times during the spin.</li><li>A Choreographic Spin has a <strong>fixed base value</strong> and will be evaluated by the judges in GOE only.</li>',

    StepSiquence: '<li>Maximum of one step sequence.</li><li>The Competitors have complete freedom in selecting the kind of step sequence they intend to execute. <li><span>Any unlisted jumps</span> of any number of revolutions and <span>listed jumps</span> with maximum one and half revolution can be included in the step sequence without any penalties.</li><li>Listed jumps of <strong>not more than one and a half revolutions</strong> included in the sequence will not be called and will not occupy a box.</li><li>Listed jumps with <strong>more than one and a half revolutions</strong> can also be included in the step sequence; they will be called and will occupy a box.</li><li>The step sequence must fully utilize the ice surface. Step sequences which are too short and barely visible cannot be considered as meeting the requirements of a step sequence.</li>',

    ChoreoSiquence: '<li>Maximum of one choreographic sequence.</li><li>A Choreographic Sequence consists of <span>at least two different skating movements</span> like spirals, arabesques, spread eagles, Ina Bauers, hydroblading, any jumps with maximum of two revolutions, spins, etc.</li><li>Steps and turns may be used to link the two or more different movements together.</li><li><span>Listed elements</span> included in the Choreographic Sequence will not be called and will not occupy a box.</li><li>The pattern is not restricted, but the sequence must be clearly visible.</li><li>The Technical Panel identifies the Choreographic Sequence which commences with the first skating movement and is concluded with the preparation to the next element (if the Choreographic Sequence is not the last element of the program).</li><li>This element has a fixed base value and will be evaluated by the judges in GOE only.</li>'
  },
  boys: {
    ProgramDuration: 'Free Skating: <strong>4 minutes</strong> (+- 10 seconds).',

    Jumps: '<li>Maximum of <strong>six</strong> jump elements (one of which must be an Axel type jump)</li><br><br><strong>Remarks:</strong><li>Individual jumps can contain any number of revolutions.</li><li>A jump combinations and jump sequence may consist of the same or another single, double, triple or quadruple jump.</li><li>There may be up to <strong>two</strong> jump combination without using an Euler (half loop) and one jump sequence in the Free Skating.</li><li>One jump combination or one jump sequence may consist of up to <strong>three</strong> jumps, the other one up to <strong>two</strong> jumps.</li><li>An Euler (half-loop) can only be executed <strong>once</strong>, in between two listed jumps, in Free Skating.</li><li>The same type of jump <strong>independent of the number of revolutions</strong> can be included not more than three times in the Free Skating program.</li><li>Any double jump (including double Axel) cannot be included <strong>more than twice</strong> in a Single’s Free Skating program (as a Solo Jump or a part of a Jump Combination / Sequence).</li><li>Of all triple and quadruple jumps only two can be executed twice. Of the two repetitions only one can be a quadruple jump or quint jump.</li><li>If both executions are as solo jumps, the second of these solo jumps will be attributed 80% of its numerical value according to the Scale of Value.</li><li>Triple and quadruple and quint jumps with the <strong>same name</strong> will be considered as <span>two</span> different jumps. No triple jump or quadruple jump or quint jump can be attempted <span>more than twice</span></li>',

    Spins: '<li>Maximum of three spins, one of which must be a <span>spin combination</span>, one a <span>flying</span> spin and one <span>choreographic</span> spin.</li><li>All Spins must be of a different character. Any Spin with the <span>same character (abbreviation)</span> as the one executed before will be deleted (but will occupy a spinning box).</li><li>The spins must have a required minimum number of revolutions: <span>six</span> for the flying spin and <span>ten</span> for the spin combination, the lack of which must be reflected by Judges in their marking. These minimum number of required revolutions must be counted from the entry of the spin until its exit (except final wind-up in Spins in one position and Flying spins).</li><li>In the spin combination the change of foot is optional.</li><li>A Choreographic Spin must have a minimum of <span>3 consecutive revolutions</span> executed on one or two blades, with any basic or non-basic positions allowed. Change of foot is optional and can be done several times during the spin.</li><li>A Choreographic Spin has a <strong>fixed base value</strong> and will be evaluated by the judges in GOE only.</li>',

    StepSiquence: '<li>Maximum of one step sequence.</li><li>The Competitors have complete freedom in selecting the kind of step sequence they intend to execute. <li><span>Any unlisted jumps</span> of any number of revolutions and <span>listed jumps</span> with maximum one and half revolution can be included in the step sequence without any penalties.</li><li>Listed jumps of <strong>not more than one and a half revolutions</strong> included in the sequence will not be called and will not occupy a box.</li><li>Listed jumps with <strong>more than one and a half revolutions</strong> can also be included in the step sequence; they will be called and will occupy a box.</li><li>The step sequence must fully utilize the ice surface. Step sequences which are too short and barely visible cannot be considered as meeting the requirements of a step sequence.</li>',

    ChoreoSiquence: '<li>Maximum of one choreographic sequence.</li><li>A Choreographic Sequence consists of <span>at least two different skating movements</span> like spirals, arabesques, spread eagles, Ina Bauers, hydroblading, any jumps with maximum of two revolutions, spins, etc.</li><li>Steps and turns may be used to link the two or more different movements together.</li><li><span>Listed elements</span> included in the Choreographic Sequence will not be called and will not occupy a box.</li><li>The pattern is not restricted, but the sequence must be clearly visible.</li><li>The Technical Panel identifies the Choreographic Sequence which commences with the first skating movement and is concluded with the preparation to the next element (if the Choreographic Sequence is not the last element of the program).</li><li>This element has a fixed base value and will be evaluated by the judges in GOE only.</li>'
  }
};








