const rulesShortCut = {
  text: 'Free Skating: <span>2:30 min. +/-10 sec.</span>',
  text1: 'Maximum of <span>five (5) jump elements</span> one of which must be an Axel type jump. There may be up to <span>two (2) jump combinations or one (1) jump combination and one (1) jump sequence</span>. Jump combinations and the jump sequence consist of two (2) jumps. In the jump sequence the second jump must be an Axel type jump with a direct step from the landing curve of the first jump into the take-off curve of the Axel jump. <span>Only one single jump and one double jump (including Double Axel) can be repeated once.</span>',
  text2: 'There must be a maximum of <span>two (2) spins</span> of a different nature (abbreviation), one of which must be a <span>spin combination</span> and one must be a spin with <span>no change of position and no change of foot</span>.The spin combination with a change of foot must have a minimum of eight (8) revolutions and without a change of foot with a minimum of six (6) revolutions. <span>Flying entry is allowed</span>. If with change of foot, only one level feature per foot will count.<br><br>The spin in one position without change of foot must have a <span>minimum of six (6) revolutions</span>, must be done in a <span>basic</span> position and will be called maximum level basic. <span>No level features are allowed in this spin</span>. 8 revolutions can be done but will not count as an attempted feature. Flying entry is not allowed.',
  text3: 'There must be a maximum of one (1) step sequence fully utilizing the ice surface and <span>including at least one skating movement such as a spiral, spread eagle, Ina Bauer, hydroblading etc.</span> If the skating movement is missing, no Level will be given. <span>At least 2 difficult turns and steps must be executed on clean edges for Level basic.</span> The Technical Panel will not award the use of body movements for at least 1/3 of the pattern feature and the two combinations of 3 difficult turns on different feet feature. ',
// Intermedia novice rules
  text4: 'Free Skating: <span>3:00 min, +/-10 sec.</span>',
  text5: 'Maximum of <span>5 jump elements</span> one of which must be an Axel type jump. There may be up to two <span>(2)jump combinations or one (1) jump combination and one (1) jump sequence.</span> Jump combinations and the jump sequence consist of <span>only two (2) jumps.</span> In the jump sequence the second jump must be an <span>Axel type jump</span> with a direct step from the landing curve of the first jump into the take-off curve of the Axel jump. One full revolution on the ice between the jumps (free foot can touch the ice, but without weight transfer) keeps the element in the frame of the definition of a jump sequence. Jumps executed in a jump sequence receive their full value. <span>No triple or quadruple jumps are allowed.</span> Only one single jump and one double jump (including Double Axel) can be repeated once.',
  text6: 'There must be a maximum of two <span>(2) spins of a different nature (abbreviation),</span> one of which must be a spin combination and one must be a spin with no change of position. The spin combination with a change of foot <span>must have a minimum of eight (8) revolutions</span> and without a change of foot with a minimum of six (6) revolutions, <span>flying entrance is not allowed.</span> If with change of foot, only one level feature per foot will count. Difficul variation of non-basic position is not counted as a feature in this spin, this will ignored by the Technical Panel.<br><br> The spin in one position with a change of foot must have a minimum of eight (8) revolutions or spin in one position without change of foot must have a minimum of six (6) revolutions, <span>flying entrance is allowed.</span> If with change of foot, only one level feature per foot will count.',
};
  
// Advance novice rules
  const advanceNoviceRules = {
    sp: {
      ProgramDuration: '<li>Short Program: <span>2:20 min, +/-10 sec</span></li>',
      Jumps: '<li>a) <span>Single Axel Paulsen or double Axel Paulsen;</span></li><li>b) <span>Double or triple jump</span>, may not repeat jump a);</li> <li>c) <span>One jump combination</span> consisting of two double jumps or one double and one triple jump, <span>the second jump must be double or triple Loop</span> (for season 2025/26), both jumps may not repeat jump a) or b).</li>',
      Spins: '<li>For girls: <span>Layback/sideways leaning spin or camel spin with no change of foot</span> (minimum six (6) revolutions) and no flying entrance (for season 2025/26).;<li>For boys: <span>Camel spin with or without change of foot</span> and no flying entrance (minimum of five (5) revolutions on each foot if change of foot, minimum of six (6) revolutions without change of foot) (for season 2025/26).</li></li><li><span>Spin combination with only one change of foot</span> (minimum of five (5) revolutions on each foot), <span>flying entrance not allowed</span>.</li>',
      StepSiquence: '<li>One step sequence fully utilizing the ice surface.</li><li> For feature 4) Two combinations of 3 difficult turns on different feet: <span>the combinations must include forward inside bracket and backward outside counter (for season 2025/26), they can be in the same combination or one in the first and the other in the second.</span></li><li> Only one difficult turn may be repeated once in the two combinations. <span>At least 2 difficult turns and steps must be executed on clean edges for Level basic.</span></li>',
    },
    fp: {
      ProgramDuration: 'Free Skating: <span>3 min, +/-10 sec.</span>', 
      Jumps: '<li>Maximum of <span>6 jump elements</span> one of which must be an Axel type jump. There may be up to two (2) jump combinations or one (1) jump combination and one (1) jump sequence.</li><li>One jump combination or jump sequence can consist of up to <span>three (3) jumps</span>, the other up to <span>two (2) jumps.</span></li><li>A jump sequence consists of <span>two or three jumps of any number of revolutions,</span> in which the second and/or the third jump is an Axel type jump with a direct step from the landing curve of the first/second jump into the take-off curve of the Axel jump.</li><li>One full revolution on the ice between the jumps (free foot can touch the ice, but without weight transfer) keeps the element in the frame of the definition of a jump sequence. Jumps executed in a jump sequence receive their full value. <span>Only two triple jumps can be repeated either in a jump combination or jump sequence.</span></li><li>No quadruple jumps are allowed. Any single, double (including Double Axel) or triple jump <span>cannot be executed more than twice in total.</span> The same type of jump independent of revolutions can be included <span>not more than three times</span> in the Free Skating program.</li>',
      Spins: '<li>There must be a <span>maximum of two (2) spins</span> of a different nature (abbreviation).</li><li> One spin must be a spin combination with a change of foot which must have a <span>minimum of eight (8) revolutions, a flying entrance is not allowed.</span></li><li>One spin must be a <span>flying camel spin</span> which must have a minimum of six (6) revolutions, a change of foot is allowed but a change of position is not allowed (for season 2024/25).</li>',
      ChoreoSiquence: 'There must be one Choreographic Sequence consisting of at least two different skating movements.'
    }
  };   
  
  // Junior Rules
  const spJuniorRules = {
    girls: {
      ProgramDuration: 'Short Program: <strong>2 minutes and 40 seconds</strong> (+- 10 seconds).',
      Jumps: '<li>Double <strong>Axel Paulsen</strong>;</li><li>Double or triple <strong>Loop</strong> jump;</li><li>Jump combination consisting of a <strong>double and a triple jump or two triple</strong> jumps;</li><br><br><span>Remarks:</span><li>Only the <strong>prescribed</strong> double or triple jump is permitted.</li><li>The jump combination may consist of the <strong>same jump or another double or triple jump</strong>. However, for all categories the jumps included <strong>must be different</strong> than the solo jump.</li>',
      Spins: '<li>Flying <strong>sit</strong> spin;</li><li><strong>Layback / sideways</strong> leaning spin or <strong>camel</strong> spin <strong>without</strong> change of foot;</li><li>Spin combination with only <strong>one</strong> change of foot;</li><br><br><span>Remarks:</span><li>Spin in <strong>one position and spin combination:</strong> if there is <strong>no spin</strong> position before and/or after the change of foot with at least <strong>three</strong> revolutions, the spin is not according to the requirements and <strong>no value</strong> will be given. <span>Except flying spins, spins cannot be commenced with a jump</span></li><li>Only the <strong>prescribed</strong> type of flying spin is permitted.</li><li>In <strong>flying spin</strong> a minimum of <strong>eight</strong> revolutions in the landing position which may be different from the flying position and which can be executed in any variation of the landing position.</li><li>In <strong>layback or sideways leaning</strong> spin any position is permitted, as long as the basic layback or sideways leaning position is maintained for <strong>eight</strong> revolutions without rising to an upright position. After the required eight revolutions it is possible to execute the Biellmann position. <span>Change of foot is not allowed.</span></li><li>In the spin in <strong>one position</strong> any variation(s) of the requite position can be executed. Minimum of <strong>eight</strong> revolutions in this position.</li><li>The spin combination must include only <strong>one</strong> change of foot with not less than <strong>six</strong> revolutions on each foot.</li>',
      StepSiquence: '<li>Step sequence <strong>fully utilizing</strong> the ice surface.</li><br><br><span>Remarks:</span><li>Unlisted jumps (any number of revolutions) and listed jumps (with maximum one revolution) <strong>may be</strong> included in the step sequence without any penalties. Listed jumps of not more than <strong>one</strong> revolution included in the sequence will not be called and will not occupy a box.'
    },
    boys: {
      ProgramDuration: 'Short Program: <strong>2 minutes and 40 seconds</strong> (+- 10 seconds).',
      Jumps: '<li>Double or triple <strong>Axel Paulsen</strong>;</li><li>Double or triple <strong>Loop</strong> jump;</li><li>Jump combination consisting of a <strong>double and a triple jump or two triple</strong> jumps;</li><br><br><span>Remarks:</span><li>When the <strong>triple Axel Paulsen</strong> is executed, it <strong>cannot</strong> be repeated again as a solo jump or in the jump combination.</li><li>Only the <strong>prescribed</strong> double or triple jump is permitted.</li><li>The jump combination may consist of the <strong>same jump or another double or triple jump</strong>. However, for all categories the jumps included <strong>must be different</strong> than the solo jump.</li>',
      Spins: '<li>Flying <strong>sit</strong> spin;</li><li><strong>Camel</strong> spin with only <strong>one</strong> change of foot;</li><li>Spin combination with only <strong>one</strong> change of foot;</li><br><br><span>Remarks:</span><li>Spin in <strong>one position and spin combination:</strong> if there is <strong>no spin</strong> position before and/or after the change of foot with at least <strong>three</strong> revolutions, the spin is not according to the requirements and <strong>no value</strong> will be given. <span>Except flying spins, spins cannot be commenced with a jump</span></li><li>Only the <strong>prescribed</strong> type of flying spin is permitted.</li><li>In <strong>flying spin</strong> a minimum of <strong>eight</strong> revolutions in the landing position which may be different from the flying position and which can be executed in any variation of the landing position.</li><li>The spin in <strong>one position</strong> must consist of only <strong>one</strong> change of foot, which may be executed in the form of a step over or a jump with not less than <strong>six</strong> revolutions on each foot in the requied basic position.</li><li>The spin combination must include only <strong>one</strong> change of foot with not less than <strong>six</strong> revolutions on each foot.</li>',
      StepSiquence: '<li>Step sequence <strong>fully utilizing</strong> the ice surface.</li><br><br><span>Remarks:</span><li>Unlisted jumps (any number of revolutions) and listed jumps (with maximum one revolution) <strong>may be</strong> included in the step sequence without any penalties. Listed jumps of not more than <strong>one</strong> revolution included in the sequence will not be called and will not occupy a box.'
    }
  };

  const fpJuniorRules = {
    girls: {
      ProgramDuration: 'Free Skating: <strong>3 minutes and 30 seconds</strong> (+- 10 seconds).',
      Jumps: 'Maximum of <strong>seven</strong> jump elements (one of which must be an <strong>Axel</strong> type jump);<br><br><span>Jump Combinations and Jump Sequences</span><li>A jump combination and a jump sequence may consist of the same or another single, double, triple or quadruple jump.</li><li>There may be up to <strong>three</strong> jump combinations or <strong>two jump combinations and one jump sequence</strong> in the Free Program.</li><li>One jump combination or one jump sequence may consist of up to <strong>three</strong> jumps, the other two up to two jumps each.</li>',
      Spins: 'Maximum of <strong>three</strong> spins, one of which must be a <strong>spin combination</strong>, one a <strong>flying spin or a spin with a flying entrance</strong> and one a spin with <strong>only one position;</strong>',
      ChoreoSiquence: 'Maximum of one choreographic sequence.'
    },
    boys: {
      ProgramDuration: 'Free Skating: <strong>3 minutes and 30 seconds</strong> (+- 10 seconds).',
      Jumps: 'Maximum of <strong>seven</strong> jump elements (one of which must be an <strong>Axel</strong> type jump);<br><br><span>Jump Combinations and Jump Sequences</span><li>A jump combination and a jump sequence may consist of the same or another single, double, triple or quadruple jump.</li><li>There may be up to <strong>three</strong> jump combinations or <strong>two jump combinations and one jump sequence</strong> in the Free Program.</li><li>One jump combination or one jump sequence may consist of up to <strong>three</strong> jumps, the other two up to two jumps each.</li>',
      Spins: 'Maximum of <strong>three</strong> spins, one of which must be a <strong>spin combination</strong>, one a <strong>flying spin or a spin with a flying entrance</strong> and one a spin with <strong>only one position;</strong>',
      ChoreoSiquence: 'Maximum of one choreographic sequence.'
    }
  };

// Senior Rules
const spSeniorRules = {
  girls: {
    ProgramDuration: 'Short Program: <strong>2 minutes and 40 seconds</strong> (+- 10 seconds).',
    Jumps: '<li>Double <strong>Axel Paulsen</strong>;</li><li>Double or triple <strong>Loop</strong> jump;</li><li>Jump combination consisting of two double jumps or one double and one triple jump or two triple jumps;</li><br><br><span>Remarks</span><li>Only the <strong>prescribed</strong> double or triple jump is permitted.</li><li>The jump combination may consist of the <span>same</span> jump or <span>another</span> double or triple jump. However, for all categories the jumps included must be <span>different</span> than the solo jump.</li><li>If the same jump is executed as a solo jump and as a part of the jump combination, the repeated jump will not be counted (if this repetition is in a jump combination, only the individual jump which is not according to the above requirements will not be counted).</li><li>If an extra jump(s) is executed, only the individual jump(s) which is not according to requirements will have no value. The jumps are considered in the order of execution.</li>',
    Spins: '<li>Flying <strong>sit</strong> spin;</li><li><strong>Layback / sideways</strong> leaning spin or <strong>camel</strong> spin <span>without</span> change of foot;</li><li><strong>Spin combination</strong> with only <span>one</span> change of foot;</li><br><br><span>Remarks</span><li>Only the prescribed type of <span>flying spin</span> or <span>spin in one position</span> is permitted.</li><li>The <strong>spin combination</strong> must include only <span>one</span> change of foot with not less than <span>six</span> revolutions on each foot.</li>',
    StepSiquence: '<span>Step sequence fully utilizing the ice surface.</span><br><br><strong>Unlisted jumps</strong> (any number of revolutions) and <strong>listed jumps</strong> (with maximum one revolution) may be included in the step sequence without any penalties. <strong>Listed jumps</strong> of not more than one revolution included in the sequence will not be called and will not occupy a box.'
  },
  boys: {
    ProgramDuration: 'Short Program: <strong>2 minutes and 40 seconds</strong> (+- 10 seconds).',
    Jumps: '<li>Double or triple <strong>Axel Paulsen</strong>;</li><li>Double or triple <strong>Loop</strong> jump;</li><li>Jump combination consisting of a double and a triple jump or two triple jumps;</li><br><br><span>Remarks</span><li>When the triple <strong>Axel Paulsen</strong> is executed, it cannot be repeated again as a solo jump or in the jump combination.</li><li>Only the <strong>prescribed</strong> double or triple jump is permitted.</li><li>The jump combination may consist of the <span>same</span> jump or <span>another</span> double or triple jump. However, for all categories the jumps included must be <span>different</span> than the solo jump.</li><li>If the same jump is executed as a solo jump and as a part of the jump combination, the repeated jump will not be counted (if this repetition is in a jump combination, only the individual jump which is not according to the above requirements will not be counted).</li><li>If an extra jump(s) is executed, only the individual jump(s) which is not according to requirements will have no value. The jumps are considered in the order of execution.</li>',
    Spins: '<li>Flying <strong>sit</strong> spin;</li><li><strong>Camel</strong> spin with only <span>one change of foot</span>;</li><li><strong>Spin combination</strong> with only <span>one change of foot</span>;</li><br><br><span>Remarks</span><li>Only the prescribed type of <span>flying spin</span> or <span>spin in one position</span> is permitted.</li><li>The <strong>spin combination</strong> must include only <span>one</span> change of foot with not less than <span>six</span> revolutions on each foot.</li>',
    StepSiquence: '<span>Step sequence fully utilizing the ice surface.</span><br><br><strong>Unlisted jumps</strong> (any number of revolutions) and <strong>listed jumps</strong> (with maximum one revolution) may be included in the step sequence without any penalties. <strong>Listed jumps</strong> of not more than one revolution included in the sequence will not be called and will not occupy a box.'
  }
};

const fpSeniorRules = {
  girls: {
    ProgramDuration: 'Free Skating: <strong>4 minutes</strong> (+- 10 seconds).',
    Jumps: '<span>Maximum of seven jump elements (one of which must be an Axel type jump)</span><br><br><strong>Individual Jumps:</strong><li>Individual jumps can contain any number of revolutions;</li><br><br><strong>Jump Combinations and Jump Sequences:</strong><li> jump combination and a jump sequence may consist of the same or another single, double, triple or quadruple jump. There may be up to three jump combinations or two jump combinations and one jump sequence in the Free Program. One jump combination or one jump sequence may consist of up to three jumps, the other two up to two jumps each;</li><br><br><strong>Repetitions:</strong><li>Any double jump (including double Axel) cannot be included more than twice in a Single’s Free Program;</li><li>Of all triple and quadruple jumps only two can be executed twice. Of the two repetitions only one can be a quadruple jump. If at least one of these executions is in a Jump Combination/ Sequence, both executions are attributed their full numerical value according to the Scale of Value and calculation process;</li><li>If both executions are as solo jumps, the second of these solo jumps will be attributed 70% of its numerical value according to the Scale of Value.  Triple and quadruple jumps with the same name will be considered as two different jumps. <strong>No triple jump or quadruple jump can be attempted more than twice.</strong></li>',
    Spins: '<strong>Maximum of three spins, one of which must be a <span>spin combination</span>, one a <span>flying spin or a spin with a flying entrance</span> and one a spin with <span>only one position.</span></strong><br><br><li>All Spins must be of a different character. <span>Any Spin with the same character (abbreviation) as the one executed before will be deleted</span> (but will occupy a spinning box).</li><li>The spins must have a required minimum number of revolutions: <span>six</span> for the flying spin and the spin with only one position and <span>ten</span> for the spin combination, the lack of which must be reflected by Judges in their marking. These minimum number of required revolutions must be counted from the entry of the spin until its exit (except final wind-up in Spins in one position and Flying spins).</li><li>In the spin combination and spin in one position the change of foot is optional.</li>',
    StepSiquence: '<span>Maximum of one step sequence.</span><br><br><li>The Competitors have complete freedom in selecting the kind of step sequence they intend to execute. <span>Any unlisted jumps</span> of any number of revolutions and <span>listed jumps</span> with maximum one revolution can be included in the step sequence without any penalties. <span>Listed jumps</span> of not more than one revolution included in the sequence will not be called and will not occupy a box.</li><li><span>Listed jumps</span> with more than one revolution can also be included in the step sequence; <span>they will be called and will occupy a box.</span></li><li>The step sequence must fully utilize the ice surface. Step sequences which are too short and barely visible cannot be considered as meeting the requirements of a step sequence.</li>',
    ChoreoSiquence: '<span>Maximum of one choreographic sequence.</span><br><br><li>A Choreographic Sequence consists of <span>at least two different skating movements</span> like spirals, arabesques, spread eagles, Ina Bauers, hydroblading, any jumps with maximum of two revolutions, spins, etc.</li><li>Steps and turns may be used to link the two or more different movements together.</li><li><span>Listed elements</span> included in the Choreographic Sequence will not be called and will not occupy a box.</li><li>The pattern is not restricted, but the sequence must be clearly visible.</li><li>The Technical Panel identifies the Choreographic Sequence which commences with the first skating movement and is concluded with the preparation to the next element (if the Choreographic Sequence is not the last element of the program).</li><li>It can be performed before or after the Step Sequence.</li><span>This element has a fixed base value and will be evaluated by the judges in GOE only.</span>'
  },
  boys: {
    ProgramDuration: 'Free Skating: <strong>4 minutes</strong> (+- 10 seconds).',
    Jumps: '<span>Maximum of seven jump elements (one of which must be an Axel type jump)</span><br><br><strong>Individual Jumps:</strong><li>Individual jumps can contain any number of revolutions;</li><br><br><strong>Jump Combinations and Jump Sequences:</strong><li> jump combination and a jump sequence may consist of the same or another single, double, triple or quadruple jump. There may be up to three jump combinations or two jump combinations and one jump sequence in the Free Program. One jump combination or one jump sequence may consist of up to three jumps, the other two up to two jumps each;</li><br><br><strong>Repetitions:</strong><li>Any double jump (including double Axel) cannot be included more than twice in a Single’s Free Program;</li><li>Of all triple and quadruple jumps only two can be executed twice. Of the two repetitions only one can be a quadruple jump. If at least one of these executions is in a Jump Combination/ Sequence, both executions are attributed their full numerical value according to the Scale of Value and calculation process;</li><li>If both executions are as solo jumps, the second of these solo jumps will be attributed 70% of its numerical value according to the Scale of Value.  Triple and quadruple jumps with the same name will be considered as two different jumps. <strong>No triple jump or quadruple jump can be attempted more than twice.</strong></li>',
    Spins: '<strong>Maximum of three spins, one of which must be a <span>spin combination</span>, one a <span>flying spin or a spin with a flying entrance</span> and one a spin with <span>only one position.</span></strong><br><br><li>All Spins must be of a different character. <span>Any Spin with the same character (abbreviation) as the one executed before will be deleted</span> (but will occupy a spinning box).</li><li>The spins must have a required minimum number of revolutions: <span>six</span> for the flying spin and the spin with only one position and <span>ten</span> for the spin combination, the lack of which must be reflected by Judges in their marking. These minimum number of required revolutions must be counted from the entry of the spin until its exit (except final wind-up in Spins in one position and Flying spins).</li><li>In the spin combination and spin in one position the change of foot is optional.</li>',
    StepSiquence: '<span>Maximum of one step sequence.</span><br><br><li>The Competitors have complete freedom in selecting the kind of step sequence they intend to execute. <span>Any unlisted jumps</span> of any number of revolutions and <span>listed jumps</span> with maximum one revolution can be included in the step sequence without any penalties. <span>Listed jumps</span> of not more than one revolution included in the sequence will not be called and will not occupy a box.</li><li><span>Listed jumps</span> with more than one revolution can also be included in the step sequence; <span>they will be called and will occupy a box.</span></li><li>The step sequence must fully utilize the ice surface. Step sequences which are too short and barely visible cannot be considered as meeting the requirements of a step sequence.</li>',
    ChoreoSiquence: '<span>Maximum of one choreographic sequence.</span><br><br><li>A Choreographic Sequence consists of <span>at least two different skating movements</span> like spirals, arabesques, spread eagles, Ina Bauers, hydroblading, any jumps with maximum of two revolutions, spins, etc.</li><li>Steps and turns may be used to link the two or more different movements together.</li><li><span>Listed elements</span> included in the Choreographic Sequence will not be called and will not occupy a box.</li><li>The pattern is not restricted, but the sequence must be clearly visible.</li><li>The Technical Panel identifies the Choreographic Sequence which commences with the first skating movement and is concluded with the preparation to the next element (if the Choreographic Sequence is not the last element of the program).</li><li>It can be performed before or after the Step Sequence.</li><span>This element has a fixed base value and will be evaluated by the judges in GOE only.</span>'
  }
};








